local builtin = require("telescope.builtin")
vim.keymap.set('n', '<leader>ff', builtin.find_files, {})
vim.keymap.set('n', '<leader>fg', builtin.live_grep, {})
vim.keymap.set('n', '<leader>fb', builtin.buffers, {})
vim.keymap.set('n', '<leader>fh', builtin.help_tags, {})
vim.keymap.set('n', '<leader>fr', "<cmd>lua require('telescope').extensions.file_browser.file_browser({hidden = true})<CR>", {noremap = true, silent = true})
vim.keymap.set('n', '<C-n>',"<cmd>:Neotree filesystem reveal left<CR>")
vim.keymap.set('n', '<C-t>',"<cmd>:Neotree toggle<CR>")
